#!/usr/bin/env bash
# Install the TiPToP × RoboLab bridge prerequisites.
#
# What this does:
#   1. Sanity-checks that TiPToP (this repo) and RoboLab (robolab_valts) are
#      already installed side-by-side.
#   2. Verifies the TiPToP pixi env is ready and M2T2 is installed.
#   3. (Optional) starts the M2T2 HTTP server in a detached tmux session.
#   4. Writes a `.env.robolab` file capturing the paths the scripts need.
#
# It does NOT install RoboLab itself (that is done via robolab_valts' own
# instructions) and it does NOT patch the RoboLab repo in any way: all
# integration lives here in `robolab/`.
#
# Usage:
#   bash robolab/install_robolab.sh                       # default layout
#   ROBOLAB_REPO=/path/to/robolab_valts bash robolab/install_robolab.sh
#   GOOGLE_API_KEY=sk-... bash robolab/install_robolab.sh
#   START_M2T2=1 bash robolab/install_robolab.sh          # also launch server

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
TIPTOP_REPO="$(cd "$HERE/.." && pwd)"
# ChicyChen fork: default to ../robolab (our fork's checkout) instead of
# upstream's ../robolab_valts. Override with ROBOLAB_REPO=... if needed.
ROBOLAB_REPO="${ROBOLAB_REPO:-$(cd "$TIPTOP_REPO/.." && pwd)/robolab}"
# Our robolab is installed into the `robolab` conda env, not a .venv.
ROBOLAB_PYTHON="${ROBOLAB_PYTHON:-$(conda run -n robolab which python 2>/dev/null || echo "$ROBOLAB_REPO/.venv/bin/python")}"
M2T2_REPO="${M2T2_REPO:-$TIPTOP_REPO/../M2T2}"
M2T2_PORT="${M2T2_PORT:-8123}"
# M2T2 doesn't ship a pixi.toml; we install it in a conda env per its README.
M2T2_CONDA_ENV="${M2T2_CONDA_ENV:-m2t2}"

say()  { printf '\033[1;36m[install]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[install]\033[0m %s\n' "$*" >&2; exit 1; }

say "TiPToP repo:   $TIPTOP_REPO"
say "RoboLab repo:  $ROBOLAB_REPO"
say "RoboLab python: $ROBOLAB_PYTHON"
say "M2T2 repo:     $M2T2_REPO"

# 1. Sanity checks
command -v pixi >/dev/null || die "pixi not in PATH. Install pixi first: https://pixi.sh"
[ -d "$TIPTOP_REPO/.pixi" ] || say "Tip: run 'pixi install' inside $TIPTOP_REPO before the first run."
[ -d "$ROBOLAB_REPO" ] || die "robolab_valts not found at $ROBOLAB_REPO (set ROBOLAB_REPO=...)"
[ -x "$ROBOLAB_PYTHON" ] || die "robolab_valts venv python not executable at $ROBOLAB_PYTHON (set ROBOLAB_PYTHON=...)"

# 2. Verify M2T2 install
# Note: upstream NVlabs/M2T2 doesn't ship `m2t2_server.py` or a pixi.toml.
# TiPToP actually expects williamshen-nz/m2t2-private (the tiptop author's
# fork). ChicyChen mirror: https://github.com/ChicyChen/m2t2-tiptop.
if [ ! -d "$M2T2_REPO" ]; then
  say "M2T2 not found at $M2T2_REPO."
  say "Clone first: git clone https://github.com/ChicyChen/m2t2-tiptop $M2T2_REPO"
  say "Then set up an env per its README:"
  say "  conda create -n $M2T2_CONDA_ENV python=3.10 -y"
  say "  conda run -n $M2T2_CONDA_ENV pip install 'setuptools<70'  # for pkg_resources"
  say "  conda run -n $M2T2_CONDA_ENV pip install torch==2.0.1 torchvision==0.15.2 \\"
  say "    --index-url https://download.pytorch.org/whl/cu117"
  say "  conda install -n $M2T2_CONDA_ENV -c nvidia/label/cuda-11.7.0 cuda-toolkit -y"
  say "  conda run -n $M2T2_CONDA_ENV pip install --no-build-isolation $M2T2_REPO/pointnet2_ops/"
  say "  conda run -n $M2T2_CONDA_ENV pip install -r $M2T2_REPO/requirements.txt"
  say "  conda run -n $M2T2_CONDA_ENV pip install $M2T2_REPO"
fi

# 3. Key file
if [ -n "${GOOGLE_API_KEY:-}" ]; then
  mkdir -p "$TIPTOP_REPO/.secrets"
  printf '%s\n' "$GOOGLE_API_KEY" > "$TIPTOP_REPO/.secrets/google_api_key"
  chmod 600 "$TIPTOP_REPO/.secrets/google_api_key"
  say "Wrote Gemini key to $TIPTOP_REPO/.secrets/google_api_key"
else
  say "No GOOGLE_API_KEY in env — set it later or pass it directly before running TiPToP."
fi

# 4. Write env file
cat > "$TIPTOP_REPO/.env.robolab" <<EOF
# Auto-generated by robolab/install_robolab.sh
export TIPTOP_REPO="$TIPTOP_REPO"
export ROBOLAB_REPO="$ROBOLAB_REPO"
export ROBOLAB_PYTHON="$ROBOLAB_PYTHON"
export M2T2_REPO="$M2T2_REPO"
export M2T2_URL="http://localhost:$M2T2_PORT"
export M2T2_CONDA_ENV="$M2T2_CONDA_ENV"
EOF
say "Wrote $TIPTOP_REPO/.env.robolab"

# 5. Optionally start M2T2 server
if [ "${START_M2T2:-0}" = "1" ]; then
  if ! command -v tmux >/dev/null; then die "tmux not installed (required for START_M2T2=1)"; fi
  if tmux has-session -t m2t2_server 2>/dev/null; then
    say "M2T2 server tmux session already exists (tmux attach -t m2t2_server)."
  else
    tmux new-session -d -s m2t2_server "cd $M2T2_REPO && conda run --no-capture-output -n $M2T2_CONDA_ENV python m2t2_server.py --port $M2T2_PORT"
    say "Started M2T2 server tmux session 'm2t2_server' on port $M2T2_PORT (conda env: $M2T2_CONDA_ENV)."
  fi
fi

say "Done. Source the env file in each shell:  source $TIPTOP_REPO/.env.robolab"
say "Then see robolab/docs/robolab.md for usage."
